apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: ivolve
type: Opaque
stringData:
  DB_PASSWORD: "ahmedpass"
  DB_ROOT_PASSWORD: "rootpass"
  JWT_SECRET: "ivolve_super_secret_jwt_key_2026"
